import assert from 'node:assert/strict';

import * as d from '../dist/domain.mjs';
const results=[];
function check(name,fn){try{fn();results.push('PASS '+name);}catch(e){results.push('FAIL '+name+' — '+e.message);process.exitCode=1;}}
const day='2026-10-09';
check('四象限新增、编辑与空标题校验',()=>{const s=d.fresh(),x=d.upsertTask(s,day,'学习',true,false);d.upsertTask(s,day,'阅读',false,true,x.id);assert.equal(d.tasks(s,day).length,1);assert.equal(x.title,'阅读');assert.equal(x.urgent,true);assert.throws(()=>d.upsertTask(s,day,' ',false,false));});
check('日期隔离和每日统计',()=>{const s=d.fresh();d.upsertTask(s,day,'今天',true,false);assert.equal(d.tasks(s,'2026-10-10').length,0);s.records.push({date:day,minutes:25});assert.equal(d.minutesOn(s,day),25);assert.equal(d.minutesOn(s,'2026-10-10'),0);});
check('完整专注奖励且不重复发放',()=>{const s=d.fresh();d.start(s,'阅读');for(let i=0;i<300;i++)d.tick(s,5,day);assert.equal(s.coins,25);assert.equal(s.records.length,1);assert.equal(s.timer.phase,'focusDone');d.tick(s,5,day);assert.equal(s.coins,25);});
check('暂停、重置与非法间隔不发金币',()=>{const s=d.fresh();d.start(s);d.tick(s,5,day);s.timer.running=false;d.tick(s,5,day);assert.equal(s.timer.remaining,1495);d.reset(s);assert.equal(s.timer.remaining,1500);d.start(s);d.tick(s,60,day);assert.equal(s.timer.running,false);assert.equal(s.coins,0);d.tick(s,NaN,day);assert.equal(s.coins,0);});
check('设置冻结本轮奖励与下一轮生效',()=>{const s=d.fresh();d.start(s);s.settings.focusMinutes=5;for(let i=0;i<300;i++)d.tick(s,5,day);assert.equal(s.coins,25);d.reset(s);assert.equal(s.timer.remaining,300);});
check('长短休息与休息不发金币',()=>{const s=d.fresh();s.timer.phase='focusDone';s.timer.cycle=4;d.startBreak(s);assert.equal(s.timer.remaining,900);for(let i=0;i<180;i++)d.tick(s,5,day);assert.equal(s.timer.phase,'breakDone');assert.equal(s.coins,0);s.timer.phase='focusDone';s.timer.cycle=1;d.startBreak(s);assert.equal(s.timer.remaining,300);});
check('跨日完成记录归入完成当天',()=>{const s=d.fresh();d.start(s);s.timer.remaining=1;d.tick(s,1,'2026-10-10');assert.equal(s.records[0].date,'2026-10-10');});
check('用眼提醒开启、关闭和重复间隔',()=>{const s=d.fresh();d.start(s);s.timer.eyeElapsed=1199;assert.equal(d.tick(s,1,day).eye,true);assert.equal(s.timer.eyeElapsed,0);assert.equal(d.tick(s,1,day).eye,undefined);s.settings.eyeEnabled=false;s.timer.eyeElapsed=1199;assert.equal(d.tick(s,1,day).eye,undefined);});
check('商店扣款一次、装备资格与余额保护',()=>{const s=d.fresh();assert.throws(()=>d.buy(s,'hat-crown'));s.coins=25;d.buy(s,'accessory-bow');assert.equal(s.coins,5);d.buy(s,'accessory-bow');assert.equal(s.coins,5);assert.equal(s.owned.length,1);assert.equal(s.pet.accessory,'accessory-bow');assert.throws(()=>d.buy(s,'unknown'));});
check('三只宠物独立命名与旧网页版存档迁移',()=>{const s=d.fresh();s.pet.kind='dog';s.pet.dogName='布丁';assert.equal(d.petName(s),'布丁');s.pet.kind='cat';assert.equal(d.petName(s),'银米');delete s.pet.dogName;delete s.alarms;const copy=d.normalize(JSON.parse(JSON.stringify(s)));assert.equal(copy.pet.dogName,'布丁');assert.deepEqual(copy.alarms,[]);});
check('刷新暂停且未知版本拒绝覆盖',()=>{const s=d.fresh();d.start(s);s.timer.remaining=132;const copy=d.normalize(JSON.parse(JSON.stringify(s)));assert.equal(copy.timer.running,false);assert.equal(copy.timer.remaining,132);assert.throws(()=>d.normalize({...s,webVersion:99}));});
check('导入修复不匹配时长和未购买装备',()=>{const s=d.fresh();s.timer.minutes=90;s.timer.duration=1;s.pet.hat='hat-crown';const copy=d.normalize(s);assert.equal(copy.timer.duration,5400);assert.equal(copy.pet.hat,'none');});
check('DDL 提前提醒一次，编辑时间后重新提醒',()=>{const s=d.fresh(),at='2026-10-10T10:00:00.000Z',x=d.upsertTask(s,day,'提交作业',true,true,null,at,30);assert.equal(d.dueReminders(s,Date.parse(at)-31*60000).length,0);assert.equal(d.dueReminders(s,Date.parse(at)-30*60000).length,1);assert.equal(d.dueReminders(s,Date.parse(at)).length,0);d.upsertTask(s,day,'提交作业',true,true,x.id,'2026-10-10T11:00:00.000Z',30);assert.equal(x.reminded,false);});
check('完成的 DDL 不提醒，跨日 DDL 仍可展示',()=>{const s=d.fresh(),x=d.upsertTask(s,day,'明日作业',true,false,null,'2026-10-10T10:00:00Z',15);assert.equal(d.upcoming(s)[0].date,day);x.done=true;assert.equal(d.upcoming(s).length,0);assert.equal(d.dueReminders(s,Date.parse('2026-10-11')).length,0);});
check('闹钟准时、关闭、重复提醒保护与刷新保留',()=>{const s=d.fresh(),at='2026-10-10T10:00:00Z',x=d.addAlarm(s,'组会',at);assert.equal(d.dueReminders(s,Date.parse(at)-1).length,0);assert.equal(d.dueReminders(s,Date.parse(at)).length,1);assert.equal(x.enabled,false);assert.equal(d.dueReminders(s,Date.parse(at)+1000).length,0);const copy=d.normalize(s);assert.equal(copy.alarms[0].notified,true);const y=d.addAlarm(s,'关闭',at);y.enabled=false;assert.equal(d.dueReminders(s,Date.parse(at)).length,0);});
check('DDL / 闹钟无效输入和恢复存档查重',()=>{const s=d.fresh();assert.throws(()=>d.addAlarm(s,'测试','invalid'));assert.throws(()=>d.addAlarm(s,' ','2026-10-10'));d.start(s);s.timer.remaining=1;d.tick(s,1,day);const copy=d.normalize(s);copy.timer.phase='focus';copy.timer.remaining=1;copy.timer.running=true;d.tick(copy,1,day);assert.equal(copy.coins,25);assert.equal(copy.records.length,1);});
console.log(results.join('\n'));console.log(`${results.filter(x=>x.startsWith('PASS')).length} / ${results.length} passed`);
